export const SEARCH_VIDEO = "SEARCH_VIDEO";
export const PUT_VIDEOS = "PUT_VIDEOS";
export const SELECT_VIDEO = "SELECT_VIDEO";
export const TOGGLE_FETCHING = "TOGGLE_FETCHING";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
